#!/usr/bin/env python
# -----------------------------------------------------------------------------
import numpy as np

import python4gmsh as p4g
# -----------------------------------------------------------------------------
def _main():
    '''Pipe with double-ring enclosure, rotated in space.
    '''

    R = p4g.rotation_matrix([1, 0, 0], np.pi/6.0)

    p4g.add_pipe(inner_radius = 0.3,
                 outer_radius = 0.4,
                 length = 1.0,
                 R = R
                 )

    x0 = np.array([0, 0, 0.3])
    p4g.add_torus(irad = 0.05, orad = 0.6, lcar = 0.1,
                  R = R,
                  x0 = np.dot(R, x0)
                  )

    x0 = np.array([0, 0, -0.3])
    p4g.add_torus(irad = 0.05, orad = 0.6, lcar = 0.1,
                  R = R,
                  x0 = np.dot(R, x0)
                  )

    print('\n'.join(p4g.GMSH_CODE))
    return
# -----------------------------------------------------------------------------
if __name__ == '__main__':
    _main()
# -----------------------------------------------------------------------------
