#!/usr/bin/env python
# -----------------------------------------------------------------------------
import numpy as np

import python4gmsh as p4g
# -----------------------------------------------------------------------------
def _main():
    '''Screw
    '''

    # Form a cross.
    X = np.array([[ 0.0,  0.5, 0.0],
                  [-0.1,  0.1, 0.0],
                  [-0.5,  0.0, 0.0],
                  [-0.1, -0.1, 0.0],
                  [ 0.0, -0.5, 0.0],
                  [ 0.1, -0.1, 0.0],
                  [ 0.5,  0.0, 0.0],
                  [ 0.1,  0.1, 0.0]])

    poly = p4g.add_polygon(X, lcar=0.05)

    axis = [0, 0, 1]
    #p4g.Extrude('Surface{%s}' % poly,
    #            translation_axis = axis
    #            )

    p4g.Extrude('Surface{%s}' % poly,
                translation_axis = axis,
                rotation_axis = axis,
                point_on_axis = [0,0,0],
                angle = 1.0/6.0*np.pi
                )

    print(p4g.get_code())
    return
# -----------------------------------------------------------------------------
if __name__ == '__main__':
    _main()
# -----------------------------------------------------------------------------
