#!/usr/bin/env python

import numpy as np

import pygmsh as pg


def _main():
    '''Main routine.
    '''

    X0 = np.array([
        [0.0,   0.0, 0.0],
        [0.5,   0.3, 0.1],
        [-0.5,  0.3, 0.1],
        [0.5,  -0.3, 0.1]
        ])

    R = np.array([0.1, 0.2, 0.1, 0.14])

    holes = []
    for x0, r in zip(X0, R):
        vol, sl = pg.add_ball(x0, r, with_volume=False, lcar=0.2*r)
        holes.append(sl)

    # pg.add_box(
    #         -1, 1,
    #         -1, 1,
    #         -1, 1,
    #         lcar=0.2,
    #         holes=holes
    #         )

    pg.add_ball(
            [0, 0, 0], 1.0,
            lcar=0.2,
            holes=holes
            )

    print(pg.get_code())
    return


if __name__ == '__main__':
    _main()
